- name: Configure nginx Container
  hosts: box
  tasks:
    - name: Clear proxy configuration 
      ansible.builtin.file:
        state: absent
        path: /home/wilnil/nginx-app/

    - name: Copy directory
      ansible.builtin.copy:
        src: nginx-app/
        dest: /home/wilnil/nginx-app

    - name: Restart nginx
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /home/wilnil/nginx-app
