version: "3.3"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # - "--entrypoints.web.http.redirections.entrypoint.permanent=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.acmewillardresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.acmewillardresolver.acme.email=will.nilges@gmail.com"
      - "--certificatesresolvers.acmewillardresolver.acme.storage=/letsencrypt/acme.json"
      #- "--certificatesresolvers.grandsvcresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

networks:
  traefik:
    name: traefik-net
