version: "3.3"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"

      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.willardresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.willardresolver.acme.dnschallenge.provider=hurricane"
      - "--log.level=DEBUG"
      - "--certificatesresolvers.willardresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.willardresolver.acme.email=wilnil@csh.rit.edu"
      - "--certificatesresolvers.willardresolver.acme.storage=/letsencrypt/acme.json"
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

networks:
  traefik:
    name: traefik-net
