version: "3.3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - traefik
    expose:
      - 3001
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=3001"
      - "traefik.http.routers.nginx.rule=Host(`status.cimmaron.willard`)"
      - "traefik.http.routers.nginx.entrypoints=web"

volumes:
  uptime-kuma-data:

networks:
  traefik:
    external: true
    name: traefik-net
