---
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: cimmaron
    environment:
      - PUID=1000
      - PGID=1000
    user: "1000"
    volumes:
      - ~/syncthing:/var/syncthing
      - type: bind
        source: ~/syncthing/immich-app/
        target: /var/immich-app/library
    network_mode: host
    restart: unless-stopped
