version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    networks:
      - nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    container_name: nextcloud
    image: nextcloud:stable-apache
    restart: always
    networks:
      - traefik
      - nextcloud
    expose:
      - 80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
        # with HTTPS
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.box.willard`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=acmewillardresolver"
        # Redirect insecure traffic
      - "traefik.http.routers.nextcloud-insecure.rule=Host(`cloud.box.willard`)"
      - "traefik.http.routers.nextcloud-insecure.entrypoints=web"
      - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-insecure.middlewares=nextcloud-https@docker"
      - "traefik.docker.network=traefik-net"

  collabora:
    container_name: collabora
    image: collabora/code:latest
    restart: always
    environment:
      - password=${COLLABORA_PASSWORD}
      - username=${COLLABORA_USERNAME}
      - aliasgroup1=https://cloud.box.willard
      - server_name=collabora.box.willard
      #- extra_params=--o:ssl.enable=true
    networks:
      - nextcloud
    expose:
      - 9980

networks:
  traefik:
    external: true
    name: traefik-net
  nextcloud:
