version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /home/wilnil/nextcloud-app/db:/var/lib/mysql
    networks:
      - nextcloud
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    user: "1000"

  nextcloud:
    container_name: nextcloud
    image: nextcloud:31-apache
    restart: always
    networks:
      - traefik
      - nextcloud
    expose:
      - 80
    links:
      - db
    volumes:
      - /home/wilnil/nextcloud-app/nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - PUID=1000
      - PGID=1000
    user: "1000"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
        # with HTTPS
      - "traefik.http.routers.nextcloud.rule=Host(`cloud.willard.gay`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      #- "traefik.http.routers.nextcloud.tls.certresolver=acmewillardresolver"
        # Redirect insecure traffic
      - "traefik.http.routers.nextcloud-insecure.rule=Host(`cloud.willard.gay`)"
      - "traefik.http.routers.nextcloud-insecure.entrypoints=web"
      - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud-insecure.middlewares=nextcloud-https@docker"
      - "traefik.docker.network=traefik-net"

  collabora:
    container_name: collabora
    image: collabora/code:latest
    restart: always
    environment:
      - password=${COLLABORA_PASSWORD}
      - username=${COLLABORA_USERNAME}
      - aliasgroup1=https://cloud.willard.gay
      - server_name=office.willard.gay
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    networks:
      - traefik
      - nextcloud
    expose:
      - 9980
    labels:
      - "traefik.enable=true"
      - "traefik.port=9980"
        # with HTTPS
      - "traefik.http.routers.collabora.rule=Host(`office.willard.gay`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.tls=true"
        # Redirect insecure traffic
      - "traefik.http.routers.collabora-insecure.rule=Host(`office.willard.gay`)"
      - "traefik.http.routers.collabora-insecure.entrypoints=web"
      - "traefik.http.middlewares.collabora-https.redirectscheme.scheme=https"
      - "traefik.http.routers.collabora-insecure.middlewares=collabora-https@docker"
      - "traefik.docker.network=traefik-net"

#  httpd:
#    image: httpd@sha256:c11efd67f6308f2c25965e4e9d13ded15e7c45c0367b95f619a16e03c6c1e2b1
#    ports:
#      - "80:80"
#    volumes:
#      - ./path/to/your/httpd.conf:/usr/local/apache2/conf/httpd.conf
#    restart: always


networks:
  traefik:
    external: true
    name: traefik-net
  nextcloud:
