- name: Configure Syncthing Container
  hosts: cimmaron
  tasks:
    - name: Make directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop:
        - /home/wilnil/syncthing-app
        - /home/wilnil/syncthing/immich-app/library
        - /home/wilnil/syncthing/immich-app/postgres
        - /home/wilnil/syncthing/nextcloud-app/nextcloud-02
        - /home/wilnil/syncthing/nextcloud-app/db
        - /home/wilnil/syncthing/trilium-app/trilium-data

    - name: Sync docker-compose.yml
      ansible.builtin.copy:
        src: syncthing-app/docker-compose.yaml
        dest: /home/wilnil/syncthing-app/docker-compose.yaml

    - name: Restart Syncthing
      ansible.builtin.command:
        cmd: docker compose up -d --force-recreate
        chdir: /home/wilnil/syncthing-app


