services:
  navidrome:
    image: deluan/navidrome@sha256:3a66e262b7ea836faa06c08ad5b32076c49e9e63e2fa4de10080c8e9be9f0846
    user: 1000:1000 # should be owner of volumes
    expose:
      - 4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      # ND_LOGLEVEL: debug
      ND_ENABLEINSIGHTSCOLLECTOR: false
    volumes:
      - "/home/wilnil/navidrome-app/data:/data"
      # - "/home/wilnil/navidrome-app/music:/music:ro"
      # Yep, this is cursed.
      - "/home/wilnil/nextcloud-app/nextcloud/data/wilnil/files/Music:/music:ro"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.port=4533"
        # with HTTPS
      - "traefik.http.routers.navidrome.rule=Host(`music.willard.gay`)"
      - "traefik.http.routers.navidrome.entrypoints=websecure"
      - "traefik.http.routers.navidrome.tls=true"
        # Redirect insecure traffic
      - "traefik.http.routers.navidrome-insecure.rule=Host(`music.willard.gay`)"
      - "traefik.http.routers.navidrome-insecure.entrypoints=web"
      - "traefik.http.middlewares.navidrome-https.redirectscheme.scheme=https"
      - "traefik.http.routers.navidrome-insecure.middlewares=navidrome-https@docker"
      - "traefik.docker.network=traefik-net"

networks:
  traefik:
    external: true
    name: traefik-net
